name: Tests
"on":
  pull_request: {}
  push:
    branches:
    - main
jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '1.x'
    - name: Run Install
      run: poetry install
    - name: Run Tests
      run: pytest --cov=./ --cov-report=xml
    - name: Report coverage
      run: bash <(curl -s https://codecov.io/bash)
